export const START_LOADING = "STATUS/START_LOADING";
export const SHOW_SUCCESS = "STATUS/SHOW_SUCCESS";
export const SHOW_ERROR = "STATUS/SHOW_ERROR";


export const LOGIN_ADMIN_SUCCUSE = "LOGIN/LOGIN_ADMIN_SUCCUSE";

export const LOGOUT_ADMIN="LOGOUT/LOGOUT_ADMIN_SUCCUSE"
